{{- if .Values.slideshow.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-slideshow
  labels:
    app: {{ .Release.Name }}-slideshow
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-slideshow
  ports:
  - name: http
    port: 80
{{- end }}
