{{- if .Values.seer.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-seer
  labels:
    app: {{ .Release.Name }}-seer
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-seer
  ports:
  - name: http
    port: 80
{{- end }}