kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ .Release.Name }}-waiter
subjects:
- kind: ServiceAccount
  name: {{ .Release.Name }}-waiter
roleRef:
  kind: Role
  name: {{ .Release.Name }}-waiter
  apiGroup: rbac.authorization.k8s.io
