apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-keycloak
  labels:
    app: {{ .Release.Name }}-keycloak
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-keycloak
  ports:
  - name: http
    port: 8080
