#!/bin/bash
set -euo pipefail
NAMESPACE=t4vd
RELEASE_NAME=t4vd
SERVICE=gateway
POD_NAME=$(kubectl get pod -n ${NAMESPACE} -l=app=${RELEASE_NAME}-$SERVICE -ojsonpath="{.items[0].metadata.name}")
kubectl exec -it -n $NAMESPACE $POD_NAME -- $SERVICE $@ 
