apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-sources
  labels:
    app: {{ .Release.Name }}-sources
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-sources
  ports:
  - name: http
    port: 80