apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  name: filters.app.bjj.ai
spec:
  group: app.bjj.ai
  scope: Namespaced
  names:
    kind: Filter
    listKind: FilterList
    plural: filters
    singular: filter
    shortNames:
      - filt
  versions:
    - name: v1alpha1
      served: true
      storage: true
      subresources:
        status: {}
      additionalPrinterColumns:
        - jsonPath: .status.phase
          name: Status
          type: string
        - jsonPath: .status.lastUpdated
          name: Age
          type: date
      schema:
        openAPIV3Schema:
          type: object
          properties:
            spec:
              type: object
              properties:
                input:
                  type: string
                  properties:
                    node:
                      type: string
                      description: "name of the input node"
                    channel:
                      type: string
                      description: "name of the output channel on the input node"
                output:
                  storage:
                    type: object
                    properties:
                      driver:
                        type: string
                        enum: [mongo, postgres]
                        description: "name of the storage driver"
                      secret:
                        type: string
                        description: "storage credentials secret"
            status:
              type: object
              properties:
                phase:
                  type: string
                  description: "brief description of the node's current state"
                message:
                  type: string
                  description: "longer description of the phase, such as an error message"
                lastProbe:
                  type: string
                  description: "timestamp of the last time the node was probed"
                lastUpdated:
                  type: string
                  description: "describes the recency of the status data"
