{{- if .Values.compiler.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ .Release.Name }}-compiler
  labels:
    app: {{ .Release.Name }}-compiler
spec:
  type: ClusterIP
  selector:
    app: {{ .Release.Name }}-compiler
  ports:
  - name: http
    port: 80
{{- end }}
